### ISSUE TITLE
File transfers do not work when connected to a Thing using a network proxy

### ISSUE THREAD

**Issue by jito-wrs** [Wind-River/device-cloud-python#242]
When connected to a Thing in devicecloud.windriver.com using an iot-connect.cfg file that includes proxy information, a file_upload attempt will fail with the following trace output on the console:

ConnectionError: ('Connection aborted.', BadStatusLine("''",))
[ERROR]:[handler:handle_work_loop:889]:    Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/device_cloud/_core/handler.py", line 886, in handle_work_loop
    self.handle_file_upload(work.data)
  File "/usr/local/lib/python2.7/dist-packages/device_cloud/_core/handler.py", line 610, in handle_file_upload
    verify=cert_location)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by element-82** [comment]
Please add some details about the proxy you are using, type etc.

**Comment by element-82** [comment]
I am testing this using an http proxy (tinyproxy) and it is working ok.  Have you duplicated the issue with a proxy server that I can use?

**Comment by element-82** [comment]
I pushed my latest changes that add proxy support to the requests module calls.  I tested with an http proxy server "tinyproxy" and I disabled all external network traffic except for dns lookups with iptables, allowing only our internal traffic so that I can ssh to the box:
```
# Proxy only traffic and internal wr traffic
# allow only a range of ips out
iptables -F
iptables -X
iptables -P INPUT DROP

# accept the wr internal network only
iptables -A INPUT -i eth0 -s 128.224.0.0/16 -j ACCEPT
iptables -A OUTPUT -i eth0 -s 128.224.0.0/16 -j ACCEPT

#accept lo input output
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -i lo -j ACCEPT

# allow dns queries
iptables -A INPUT -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --sport 53 -j ACCEPT

```

I monitored the proxy server's log file and I triggered a large file transfer (200MB).  I can see all pkts going through the proxy server.  The URL is unreachable without the latest fix in my test.

**Comment by element-82** [comment]
This should be closed now.
